### ISSUE TITLE
Mangtaps

### ISSUE THREAD

**Issue by MFarelS** [bluesky322/flasher2#6]
flasher1 nya ngape dihapus bang

**Comment by Gimenz** [comment]
> flasher1 nya ngape dihapus bang

berbahaya sloerd

**Comment by MFarelS** [comment]
> > flasher1 nya ngape dihapus bang
> 
> berbahaya sloerd

Barter rdp

**Comment by MFarelS** [comment]
> > flasher1 nya ngape dihapus bang
> 
> berbahaya sloerd

Awokawoakwoao ajg

**Comment by Gimenz** [comment]
> > > flasher1 nya ngape dihapus bang
> > 
> > 
> > berbahaya sloerd
> 
> Barter rdp

g dlu

**Comment by 434fajar434** [comment]
Ko di gua bot saat ini tidak tersedia ya?

**Comment by MFarelS** [comment]
> > > > flasher1 nya ngape dihapus bang
> > > 
> > > 
> > > berbahaya sloerd
> > 
> > 
> > Barter rdp
> 
> g dlu

Okoklh lagi mantau bg?

**Comment by MFarelS** [comment]
> Ko di gua bot saat ini tidak tersedia ya?

Gtw

**Comment by abrekok** [comment]
> > > flasher1 nya ngape dihapus bang
> > 
> > 
> > berbahaya sloerd
> 
> Barter rdp

pakai rdp apa om, 
saya pakai aws ping ke shopee 14 detikan

**Comment by MFarelS** [comment]
> > > > flasher1 nya ngape dihapus bang
> > > 
> > > 
> > > berbahaya sloerd
> > 
> > 
> > Barter rdp
> 
> pakai rdp apa om,
> saya pakai aws ping ke shopee 14 detikan

Pake termos 1.4 detik

**Comment by MFarelS** [comment]
> > > > flasher1 nya ngape dihapus bang
> > > 
> > > 
> > > berbahaya sloerd
> > 
> > 
> > Barter rdp
> 
> pakai rdp apa om,
> saya pakai aws ping ke shopee 14 detikan

Sama aws
1.5 detik

**Comment by abrekok** [comment]
> > > > > flasher1 nya ngape dihapus bang
> > > > 
> > > > 
> > > > berbahaya sloerd
> > > 
> > > 
> > > Barter rdp
> > 
> > 
> > pakai rdp apa om,
> > saya pakai aws ping ke shopee 14 detikan
> 
> Sama aws
> 1.5 detik

kalau lagi normal bisa 1-2 detik, 
tapi kalau waktunya flash sale bisa sampai 14 detikan.

ada yang bisa stabil di 1detik, pas saya tanya gak ngasih tau

**Comment by NolPixel** [comment]
![IMG_20210711_214547](https://user-images.githubusercontent.com/41100835/125199680-87b73c00-e291-11eb-8b1a-c57841cc9e21.jpg)
Crot ah

**Comment by abrekok** [comment]
> ![IMG_20210711_214547](https://user-images.githubusercontent.com/41100835/125199680-87b73c00-e291-11eb-8b1a-c57841cc9e21.jpg)
> Crot ah

bisikin dong gan
